// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaitynoLab.Server.Data;

#nullable disable

namespace SaitynoLab.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221012173538_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SaitynoLab.Shared.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<bool>("ToAssemble")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Furniture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kėdė v1",
                            OrderId = 1,
                            ToAssemble = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kėdė v2",
                            OrderId = 1,
                            ToAssemble = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stalas v1",
                            OrderId = 1,
                            ToAssemble = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stalas v2",
                            OrderId = 2,
                            ToAssemble = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "Knygų lentyna v1",
                            OrderId = 2,
                            ToAssemble = true
                        });
                });

            modelBuilder.Entity("SaitynoLab.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerId = 1,
                            DateCreated = new DateTime(2022, 10, 12, 20, 35, 38, 251, DateTimeKind.Local).AddTicks(3543),
                            Email = "cclaire0@cloudflare.com",
                            IsCompleted = false,
                            PhoneNumber = "+55 575 366 5029"
                        },
                        new
                        {
                            Id = 2,
                            BuyerId = 1,
                            DateCreated = new DateTime(2022, 10, 12, 20, 35, 38, 251, DateTimeKind.Local).AddTicks(3575),
                            Email = "odagleas1@desdev.cn",
                            IsCompleted = false,
                            PhoneNumber = "+55 126 791 9151"
                        },
                        new
                        {
                            Id = 3,
                            BuyerId = 1,
                            DateCreated = new DateTime(2022, 10, 12, 20, 35, 38, 251, DateTimeKind.Local).AddTicks(3577),
                            Email = "chanson2@adobe.com",
                            IsCompleted = false,
                            PhoneNumber = "+351 451 804 0946"
                        },
                        new
                        {
                            Id = 4,
                            BuyerId = 2,
                            DateCreated = new DateTime(2022, 10, 12, 20, 35, 38, 251, DateTimeKind.Local).AddTicks(3579),
                            Email = "cbastiman3@bbb.org",
                            IsCompleted = false,
                            PhoneNumber = "+46 907 344 5728"
                        },
                        new
                        {
                            Id = 5,
                            BuyerId = 2,
                            DateCreated = new DateTime(2022, 10, 12, 20, 35, 38, 251, DateTimeKind.Local).AddTicks(3582),
                            Email = "lsafont4@ezinearticles.com",
                            IsCompleted = false,
                            PhoneNumber = "+7 509 606 2496"
                        });
                });

            modelBuilder.Entity("SaitynoLab.Shared.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 5,
                            FurnitureId = 1,
                            Name = "Kėdės kojos V1",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Color = 5,
                            FurnitureId = 2,
                            Name = "Kėdės kojos V2",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 3,
                            Color = 5,
                            FurnitureId = 1,
                            Name = "Stalo kojos V1",
                            Price = 20.989999999999998
                        },
                        new
                        {
                            Id = 4,
                            Color = 5,
                            FurnitureId = 2,
                            Name = "Stalo kojos V2",
                            Price = 20.989999999999998
                        },
                        new
                        {
                            Id = 5,
                            Color = 5,
                            FurnitureId = 1,
                            Name = "Kėdės viršus V1",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 6,
                            Color = 5,
                            FurnitureId = 2,
                            Name = "Kėdės viršus V2",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 7,
                            Color = 5,
                            FurnitureId = 1,
                            Name = "Stalo viršus V1",
                            Price = 17.989999999999998
                        },
                        new
                        {
                            Id = 8,
                            Color = 5,
                            FurnitureId = 2,
                            Name = "Stalo viršus V1",
                            Price = 18.989999999999998
                        });
                });

            modelBuilder.Entity("SaitynoLab.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
